name: Auto Merge Any Branch to Main

on:
  push:
    branches-ignore:
      - main  # Do not trigger on pushes to main itself

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and branches

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get current branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge current branch into main (Ultra-Loose)
        run: |
          BRANCH_NAME=${{ steps.get_branch.outputs.branch_name }}
          echo "⚙️ Merging $BRANCH_NAME into main..."

          # Fetch the specific branch to ensure it's available locally
          git fetch origin $BRANCH_NAME:$BRANCH_NAME || {
            echo "⚠️ Branch '$BRANCH_NAME' not found on remote. Skipping merge."
            exit 0
          }

          # Checkout or create 'main' branch
          git checkout main || git checkout -b main

          # Try to merge the branch, allow unrelated histories, and prevent job failure
          git merge $BRANCH_NAME --allow-unrelated-histories -m "🤖 Auto-merged $BRANCH_NAME into main" || {
            echo "⚠️ Merge failed for branch '$BRANCH_NAME'. Skipping..."
            exit 0
          }

          # Attempt to push; ignore failures gracefully
          git push origin main || {
            echo "⚠️ Push to main failed or nothing to push."
            exit 0
          }
