name: Auto Merge Any Branch to Main

on:
  push:
    branches-ignore:
      - main  # Do not trigger on pushes to main itself

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and branches

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get current branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Fetch all branches
        run: git fetch --all

      - name: Try merging into main (ultra-loose)
        run: |
          BRANCH_NAME=${{ steps.get_branch.outputs.branch_name }}
          echo "Trying to merge $BRANCH_NAME into main..."

          git checkout main || git checkout -b main
          
          # Attempt to merge - ignore failures and unrelated history
          git merge origin/$BRANCH_NAME --allow-unrelated-histories -m "Auto-merged $BRANCH_NAME into main" || {
            echo "⚠️ Merge failed or branch not found: origin/$BRANCH_NAME. Skipping without failing job."
            exit 0
          }

          git push origin main || {
            echo "⚠️ Push to main failed. Skipping without failing job."
            exit 0
          }
